name: Build Angular App

on:
  pull_request
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build:acc
